// <auto-generated />
using System;
using Garage_2._0.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Garage_2._0.Migrations
{
    [DbContext(typeof(Garage_2_0Context))]
    [Migration("20251223102158_InitClean")]
    partial class InitClean
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Garage_2._0.Models.ParkedVehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ArrivalTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberOfWheels")
                        .HasColumnType("int");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("SpotNumber")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ParkedVehicle");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            ArrivalTime = new DateTime(2025, 12, 18, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Brand = "Volvo",
                            Color = "Blue",
                            Model = "XC60",
                            Note = "Test car",
                            NumberOfWheels = 4,
                            RegistrationNumber = "ABC123",
                            SpotNumber = 1,
                            Type = 0
                        },
                        new
                        {
                            Id = -2,
                            ArrivalTime = new DateTime(2025, 12, 18, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Brand = "BMW",
                            Color = "Black",
                            Model = "R1250",
                            Note = "Test motorcycle",
                            NumberOfWheels = 2,
                            RegistrationNumber = "XYZ789",
                            SpotNumber = 2,
                            Type = 1
                        },
                        new
                        {
                            Id = -3,
                            ArrivalTime = new DateTime(2025, 12, 17, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            Brand = "Toyota",
                            Color = "Red",
                            Model = "Corolla",
                            Note = "Compact car",
                            NumberOfWheels = 4,
                            RegistrationNumber = "JKL456",
                            SpotNumber = 3,
                            Type = 0
                        },
                        new
                        {
                            Id = -4,
                            ArrivalTime = new DateTime(2025, 12, 16, 8, 15, 0, 0, DateTimeKind.Unspecified),
                            Brand = "Scania",
                            Color = "White",
                            Model = "R500",
                            Note = "Heavy duty truck",
                            NumberOfWheels = 6,
                            RegistrationNumber = "MNO321",
                            SpotNumber = 4,
                            Type = 6
                        });
                });

            modelBuilder.Entity("Garage_2._0.Models.ParkingSpot", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("MotorcycleCount")
                        .HasColumnType("int");

                    b.Property<int>("SpotNumber")
                        .HasColumnType("int");

                    b.Property<int?>("VehicleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VehicleId");

                    b.ToTable("ParkingSpot");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MotorcycleCount = 0,
                            SpotNumber = 1,
                            VehicleId = -1
                        },
                        new
                        {
                            Id = 2,
                            MotorcycleCount = 1,
                            SpotNumber = 2,
                            VehicleId = -2
                        },
                        new
                        {
                            Id = 3,
                            MotorcycleCount = 0,
                            SpotNumber = 3,
                            VehicleId = -3
                        },
                        new
                        {
                            Id = 4,
                            MotorcycleCount = 0,
                            SpotNumber = 4,
                            VehicleId = -4
                        },
                        new
                        {
                            Id = 5,
                            MotorcycleCount = 0,
                            SpotNumber = 5,
                            VehicleId = -4
                        },
                        new
                        {
                            Id = 6,
                            MotorcycleCount = 0,
                            SpotNumber = 6
                        },
                        new
                        {
                            Id = 7,
                            MotorcycleCount = 0,
                            SpotNumber = 7
                        },
                        new
                        {
                            Id = 8,
                            MotorcycleCount = 0,
                            SpotNumber = 8
                        },
                        new
                        {
                            Id = 9,
                            MotorcycleCount = 0,
                            SpotNumber = 9
                        },
                        new
                        {
                            Id = 10,
                            MotorcycleCount = 0,
                            SpotNumber = 10
                        },
                        new
                        {
                            Id = 11,
                            MotorcycleCount = 0,
                            SpotNumber = 11
                        },
                        new
                        {
                            Id = 12,
                            MotorcycleCount = 0,
                            SpotNumber = 12
                        },
                        new
                        {
                            Id = 13,
                            MotorcycleCount = 0,
                            SpotNumber = 13
                        },
                        new
                        {
                            Id = 14,
                            MotorcycleCount = 0,
                            SpotNumber = 14
                        },
                        new
                        {
                            Id = 15,
                            MotorcycleCount = 0,
                            SpotNumber = 15
                        },
                        new
                        {
                            Id = 16,
                            MotorcycleCount = 0,
                            SpotNumber = 16
                        },
                        new
                        {
                            Id = 17,
                            MotorcycleCount = 0,
                            SpotNumber = 17
                        },
                        new
                        {
                            Id = 18,
                            MotorcycleCount = 0,
                            SpotNumber = 18
                        },
                        new
                        {
                            Id = 19,
                            MotorcycleCount = 0,
                            SpotNumber = 19
                        },
                        new
                        {
                            Id = 20,
                            MotorcycleCount = 0,
                            SpotNumber = 20
                        });
                });

            modelBuilder.Entity("Garage_2._0.Models.ParkingSpot", b =>
                {
                    b.HasOne("Garage_2._0.Models.ParkedVehicle", "Vehicle")
                        .WithMany()
                        .HasForeignKey("VehicleId");

                    b.Navigation("Vehicle");
                });
#pragma warning restore 612, 618
        }
    }
}
