// <auto-generated />
using System;
using Garage_2._0.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Garage_2._0.Migrations
{
    [DbContext(typeof(Garage_2_0Context))]
    [Migration("20260114135215_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Garage_2._0.Models.ParkedVehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ArrivalTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberOfWheels")
                        .HasColumnType("int");

                    b.Property<string>("ParkingSpots")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ParkedVehicle");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            ArrivalTime = new DateTime(2025, 12, 18, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Brand = "Volvo",
                            Color = "Blue",
                            Model = "XC60",
                            Note = "",
                            NumberOfWheels = 4,
                            ParkingSpots = "1",
                            RegistrationNumber = "ABC123",
                            Type = 0
                        },
                        new
                        {
                            Id = -2,
                            ArrivalTime = new DateTime(2025, 12, 18, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Brand = "BMW",
                            Color = "Black",
                            Model = "R1250",
                            Note = "",
                            NumberOfWheels = 2,
                            ParkingSpots = "5,A",
                            RegistrationNumber = "XYZ789",
                            Type = 1
                        },
                        new
                        {
                            Id = -3,
                            ArrivalTime = new DateTime(2025, 12, 17, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            Brand = "Toyota",
                            Color = "Red",
                            Model = "Corolla",
                            Note = "",
                            NumberOfWheels = 4,
                            ParkingSpots = "3",
                            RegistrationNumber = "JKL456",
                            Type = 0
                        },
                        new
                        {
                            Id = -4,
                            ArrivalTime = new DateTime(2025, 12, 16, 8, 15, 0, 0, DateTimeKind.Unspecified),
                            Brand = "Scania",
                            Color = "White",
                            Model = "R500",
                            Note = "",
                            NumberOfWheels = 6,
                            ParkingSpots = "10,11",
                            RegistrationNumber = "MNO321",
                            Type = 6
                        },
                        new
                        {
                            Id = -5,
                            ArrivalTime = new DateTime(2025, 12, 17, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Brand = "Mercedes",
                            Color = "Yellow",
                            Model = "Citaro",
                            Note = "",
                            NumberOfWheels = 6,
                            ParkingSpots = "15",
                            RegistrationNumber = "BUS999",
                            Type = 2
                        },
                        new
                        {
                            Id = -6,
                            ArrivalTime = new DateTime(2025, 12, 18, 11, 30, 0, 0, DateTimeKind.Unspecified),
                            Brand = "Harley Davidson",
                            Color = "Red",
                            Model = "Street 750",
                            Note = "",
                            NumberOfWheels = 2,
                            ParkingSpots = "5,B",
                            RegistrationNumber = "MC555",
                            Type = 1
                        },
                        new
                        {
                            Id = -7,
                            ArrivalTime = new DateTime(2025, 12, 18, 13, 15, 0, 0, DateTimeKind.Unspecified),
                            Brand = "Audi",
                            Color = "Silver",
                            Model = "A4",
                            Note = "",
                            NumberOfWheels = 4,
                            ParkingSpots = "7",
                            RegistrationNumber = "DEF789",
                            Type = 0
                        },
                        new
                        {
                            Id = -8,
                            ArrivalTime = new DateTime(2025, 12, 15, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Brand = "Yamaha",
                            Color = "White",
                            Model = "242X",
                            Note = "",
                            NumberOfWheels = 0,
                            ParkingSpots = "20,21,22",
                            RegistrationNumber = "BOAT123",
                            Type = 4
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
